const yakuList = [
  "Tsumo",
  "Riichi",
  "Ippatsu",
  "Chankan",
  "Rinshan",
  "Haitei",
  "Houtei",
  "Pinfu",
  "Tanyao",
  "Ippeiko",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Yakuhai",
  "Daburu Riichi",
  "Chiitoi",
  "Chanta",
  "Itsuu",
  "Sanshoku Doujun",
  "Sanshoku Doukou",
  "Sankantsu",
  "Toitoi",
  "Sanankou",
  "Shousangen",
  "Honrouto",
  "Ryanpeikou",
  "Junchan",
  "Honitsu",
  "Chinitsu",
  "Renhou",
  "Tenhou",
  "Chihou",
  "Daisangen",
  "Suuankou",
  "Suuankou",
  "Tsuiisou",
  "Ryuuiisou",
  "Chinrouto",
  "Chuuren poutou",
  "Chuuren poutou (Nine tile wait)",
  "Kokushi musou",
  "Kokushi musou (13 tile wait)",
  "Daisuushi",
  "Shousuushi",
  "Suukantsu",
  "Dora",
  "Uradora",
  "Akadora",
];

/**
 * @param {string} tileString - A tile represented as one number and one letter (for the suit) e.g. 5s|1h|8p etc.
 * @returns {string} - The URL of the tile required
 */
export function YakuIdToName(yakuId) {
  const ID = parseInt(yakuId);
  return yakuList[ID];
}
